DOMAIN = "linktap"
STATUS_CMD = 3
START_CMD = 6
STOP_CMD = 7
CONFIG_CMD = 16
DISMISS_ALERT_CMD = 10
TAP_ID = "ID of Tap"
GW_ID = "ID of Gateway"
GW_IP = "Local IP Address of Gateway"
NAME = "Friendly Name of Tap"
DEFAULT_TIME = 900
DEFAULT_NAME = "Linktap Local Integration"
PLATFORMS = ['switch', 'binary_sensor', 'sensor', 'number']
ATTR_TIME = 'Default Time'
ATTR_DURATION = "Watering Duration"
ATTR_STATE = "is_watering"
MANUFACTURER = "Linktap"